version: '3.8'

services:
  user_profile_db:
    image: mysql:8.0
    container_name: mysql_user_profile
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: user_profile_db
    ports:
      - "3306:3306"

  user_additional_info_db:
    image: mysql:8.0
    container_name: mysql_user_additional_info
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: user_additional
    ports:
      - "3307:3306"
